[[nodejs_app]]
arch = "x86_64"
git-tree-sha1 = "6460883d771aad2be8082172187a886c663a8a80"
libc = "glibc"
os = "linux"

    [[nodejs_app.download]]
    sha256 = "81bcb20ccbdb2060708b6562697c8ceaeb3e8ed497b067dc23fdac3f657dbf69"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v12.22.1%2B0/NodeJS-12.22.1+0-x86_64-linux-gnu.tar.gz"
[[nodejs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1c4bb0610560c0fe96cf1abc7246ec0a98a435f4"
libc = "glibc"
os = "linux"

    [[nodejs_app.download]]
    sha256 = "74c83c5e9fcf6d22c8e6227726fecb62055346434e877a11de66804b97c1214b"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v12.22.1%2B0/NodeJS-12.22.1+0-armv7l-linux-gnueabihf.tar.gz"
[[nodejs_app]]
arch = "powerpc64le"
git-tree-sha1 = "930fd069bc798da127297b51493548b5a9852e19"
libc = "glibc"
os = "linux"

    [[nodejs_app.download]]
    sha256 = "db6bfba01558bfde4e0be88e74e63026737b82300868d4c64124a28d79cc4a87"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v12.22.1%2B0/NodeJS-12.22.1+0-powerpc64le-linux-gnu.tar.gz"
[[nodejs_app]]
arch = "x86_64"
git-tree-sha1 = "6460883d771aad2be8082172187a886c663a8a80"
libc = "musl"
os = "linux"

    [[nodejs_app.download]]
    sha256 = "21735e1b67c78f3f46e6e1d888a1a30a2bdc274a9474f71595f28962681ba954"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v12.22.1%2B0/NodeJS-12.22.1+0-x86_64-linux-musl.tar.gz"
[[nodejs_app]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1c4bb0610560c0fe96cf1abc7246ec0a98a435f4"
libc = "musl"
os = "linux"

    [[nodejs_app.download]]
    sha256 = "0d4ec2a67c985c358edd5aed9d80f0c39239b5baf8a2b133e960b8370455cbc0"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v12.22.1%2B0/NodeJS-12.22.1+0-armv7l-linux-musleabihf.tar.gz"
[[nodejs_app]]
arch = "x86_64"
git-tree-sha1 = "ca4c5ab9451bccd1ba4f8d797bc675f390e1bddb"
os = "macos"

    [[nodejs_app.download]]
    sha256 = "a1e16fa208fdfed4f38ecd23a38d5cf1a41022445eca96fb330883a0d5c7d4cf"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v12.22.1%2B0/NodeJS-12.22.1+0-x86_64-apple-darwin14.tar.gz"
[[nodejs_app]]
arch = "aarch64"
git-tree-sha1 = "ca4c5ab9451bccd1ba4f8d797bc675f390e1bddb"
os = "macos"

    [[nodejs_app.download]]
    sha256 = "db835abffe926d6d48528eee35c578092c927a4f178596f06dffedb322ba0ae4"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v12.22.1%2B0/NodeJS-12.22.1+0-aarch64-apple-darwin14.tar.gz"
[[nodejs_app]]
arch = "i686"
git-tree-sha1 = "918bec4ac0349ed58873367b9292ff716a4a2a5d"
os = "windows"

    [[nodejs_app.download]]
    sha256 = "bf61baa1414466071c351ba35273da9cae26b3784b6b6239f94dd40e7913ad7f"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v12.22.1%2B0/NodeJS-12.22.1+0-i686-w64-mingw32.tar.gz"
[[nodejs_app]]
arch = "x86_64"
git-tree-sha1 = "0bd56198ac47b98572257a7725d9425f5a1ba1a9"
os = "windows"

    [[nodejs_app.download]]
    sha256 = "e79261af3c0b38eb49f84a722a91e0cbe556fa520c4496faa4afc1cc99425ea9"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v12.22.1%2B0/NodeJS-12.22.1+0-x86_64-w64-mingw32.tar.gz"
