[[nodejs_app]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c278c61d6242d19deca58e582fc6a6f0a727de8"
libc = "glibc"
os = "linux"

    [[nodejs_app.download]]
    sha256 = "fc383b80b866a56d99c405dcf3ab211cd0acdd53d6b54539d1507e2c2b9844b5"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v18.16.0%2B0/NodeJS-18.16.0+0-x86_64-linux-gnu.tar.gz"
[[nodejs_app]]
arch = "armv7l"
cxxstring_abi = "cxx11"
call_abi = "eabihf"
git-tree-sha1 = "3b42737df880fea84d10da846bb55e3fe060451b"
libc = "glibc"
os = "linux"

    [[nodejs_app.download]]
    sha256 = "10972db5a400e543b5cced520a2c22fb14dd58c2ff5f2caac1e471270be8e73e"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v18.16.0%2B0/NodeJS-18.16.0+0-armv7l-linux-gnueabihf.tar.gz"
[[nodejs_app]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dadd6f7fc21de75589681d1b7fa3fc16a1ea1f6b"
libc = "glibc"
os = "linux"

    [[nodejs_app.download]]
    sha256 = "8487d0f21c8afe378d20d6620b5cd1717b272358d8485f13fec2ed5e13e10731"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v18.16.0%2B0/NodeJS-18.16.0+0-powerpc64le-linux-gnu.tar.gz"
[[nodejs_app]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c278c61d6242d19deca58e582fc6a6f0a727de8"
libc = "musl"
os = "linux"

    [[nodejs_app.download]]
    sha256 = "9975f5cf5db1ef253aa1cc2c9c0d89e77157957ca9514e17eec613e62e3396da"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v18.16.0%2B0/NodeJS-18.16.0+0-x86_64-linux-musl.tar.gz"
[[nodejs_app]]
arch = "armv7l"
cxxstring_abi = "cxx11"
call_abi = "eabihf"
git-tree-sha1 = "3b42737df880fea84d10da846bb55e3fe060451b"
libc = "musl"
os = "linux"

    [[nodejs_app.download]]
    sha256 = "775a410e4ffc07807a9fba1083072ce4f1d8d6f1031f3d0a7229b023bc14c3f6"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v18.16.0%2B0/NodeJS-18.16.0+0-armv7l-linux-musleabihf.tar.gz"
[[nodejs_app]]
arch = "x86_64"
git-tree-sha1 = "ec20cc6a0357122187307d46d3c0936393304795"
os = "macos"

    [[nodejs_app.download]]
    sha256 = "7291a40884a395057e0374f6ba238ee5360c620e1ee36753ffc8be157cac9021"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v18.16.0%2B0/NodeJS-18.16.0+0-x86_64-apple-darwin14.tar.gz"
[[nodejs_app]]
arch = "aarch64"
git-tree-sha1 = "ec20cc6a0357122187307d46d3c0936393304795"
os = "macos"

    [[nodejs_app.download]]
    sha256 = "16a2c64c86441cbda737700649398ce9717d53279adabfd76ffc1e832b1e0844"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v18.16.0%2B0/NodeJS-18.16.0+0-aarch64-apple-darwin14.tar.gz"
[[nodejs_app]]
arch = "i686"
git-tree-sha1 = "ae40ec822f0b29ca9d32e97969cbf8975e0642b2"
os = "windows"

    [[nodejs_app.download]]
    sha256 = "19d073d6225a446734c614381d8566a7781c1196f64f9904b2208b7d074aca87"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v18.16.0%2B0/NodeJS-18.16.0+0-i686-w64-mingw32.tar.gz"
[[nodejs_app]]
arch = "x86_64"
git-tree-sha1 = "926ad314605433096abebe5aca612ffbee1347b8"
os = "windows"

    [[nodejs_app.download]]
    sha256 = "c59705957770f721c3b0009afac337bf0c275a8705b4b1a3969f79e947a53afe"
    url = "https://github.com/davidanthoff/NodeJSBuilder/releases/download/v18.16.0%2B0/NodeJS-18.16.0+0-x86_64-w64-mingw32.tar.gz"
